// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] 
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BUJ9OZz5rDcRA3w5dlxO2ufhfgJykSA',
    appId: '1:75661978047:web:fd3fbda2ea6bc572c1590a',
    messagingSenderId: '75661978047',
    projectId: 'smart-harvest-f27d4',
    authDomain: 'smart-harvest-f27d4.firebaseapp.com',
    storageBucket: 'smart-harvest-f27d4.firebasestorage.app',
    measurementId: 'G-0LWYLNRRBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOl0lumNZ9a7SKiDUFUuDhDW6ca7UFcYQ',
    appId: '1:75661978047:android:2351804904e3bcc9c1590a',
    messagingSenderId: '75661978047',
    projectId: 'smart-harvest-f27d4',
    storageBucket: 'smart-harvest-f27d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE1kD15Td9NhkA_pz0VNE77aTzAXHByW4',
    appId: '1:75661978047:ios:e93412020958f169c1590a',
    messagingSenderId: '75661978047',
    projectId: 'smart-harvest-f27d4',
    storageBucket: 'smart-harvest-f27d4.firebasestorage.app',
    iosBundleId: 'com.example.smartHarvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE1kD15Td9NhkA_pz0VNE77aTzAXHByW4',
    appId: '1:75661978047:ios:e93412020958f169c1590a',
    messagingSenderId: '75661978047',
    projectId: 'smart-harvest-f27d4',
    storageBucket: 'smart-harvest-f27d4.firebasestorage.app',
    iosBundleId: 'com.example.smartHarvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1BUJ9OZz5rDcRA3w5dlxO2ufhfgJykSA',
    appId: '1:75661978047:web:0fe81f8dd0793dd0c1590a',
    messagingSenderId: '75661978047',
    projectId: 'smart-harvest-f27d4',
    authDomain: 'smart-harvest-f27d4.firebaseapp.com',
    storageBucket: 'smart-harvest-f27d4.firebasestorage.app',
    measurementId: 'G-HGPLTPFWXC',
  );
}
